@startuml
' Диаграмма деятельности - Процесс работы

start
:Запуск программы;

:Загрузка данных из JSON;
if (Файл существует?) then (Да)
    :Загрузка записей;
else (Нет)
    :Создание пустого списка;
endif

while (Приложение работает?) is (Да)
    :Показать главное меню;
    :Ожидание выбора пользователя;
    
    if (Выбор = "1") then (Добавить запись)
        :Запрос данных у пользователя;
        :Валидация ввода;
        :Создание записи;
        :Сохранение в JSON;
        :Сообщение об успехе;
        
    elseif (Выбор = "2") then (Показать все записи)
        :Отображение всех записей;
        
    elseif (Выбор = "3") then (Показать отчет)
        :Расчет баланса;
        :Расчет доходов и расходов;
        :Группировка по категориям;
        :Отображение отчета;
        
    elseif (Выбор = "4") then (Показать статистику)
        :Расчет средней суммы;
        :Расчет максимумов;
        :Отображение статистики;
        
    elseif (Выбор = "5") then (Удалить запись)
        :Показать список записей;
        :Выбор номера записи;
        :Удаление записи;
        :Сохранение в JSON;
        
    elseif (Выбор = "6") then (Редактировать запись)
        :Показать список записей;
        :Выбор номера записи;
        :Запрос новых данных;
        :Обновление записи;
        :Сохранение в JSON;
        
    elseif (Выбор = "7") then (Поиск по категории)
        :Ввод категории;
        :Фильтрация записей;
        :Отображение результатов;
        
    elseif (Выбор = "8") then (Фильтр по типу)
        :Выбор типа (Доход/Расход);
        :Фильтрация записей;
        :Отображение результатов;
        
    elseif (Выбор = "9") then (Экспорт в CSV)
        :Создание CSV файла;
        :Сохранение записей;
        :Сообщение об экспорте;
        
    elseif (Выбор = "10") then (Показать путь)
        :Отображение пути к файлу;
        
    elseif (Выбор = "0") then (Выход)
        :Сохранение данных;
        :Сообщение о выходе;
        break;
        
    else (Неверный выбор)
        :Сообщение об ошибке;
    endif
endwhile (Нет)

:Завершение программы;
stop
@enduml